package com.euler;

public class Problem2 {

    /**
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     */
    public int run() {
        int limit = 4000000;
        return fibonacci(limit, 0,1);
    }

    public int fibonacci(int limit, int firstTerm, int secondTerm) {
        if(firstTerm + secondTerm > limit) {
            return (firstTerm + secondTerm % 2 == 0) ? firstTerm + secondTerm : 0;
        }
        if((firstTerm + secondTerm) % 2 == 0) {
            return firstTerm + secondTerm + fibonacci(limit, secondTerm, firstTerm + secondTerm);
        }
        return fibonacci(limit, secondTerm, firstTerm + secondTerm);
    }
}
